### ISSUE TITLE
Hi thanks for the example, but I got a connection refused error running the code 

### ISSUE THREAD

**Issue by walterwang** [thebillington/pygame_multiplayer_server#1]
When running the code, I got this error, could not find the reason why. 
{'error': ConnectionRefusedError(111, 'Connection refused'), 'action': 'error'}

**Comment by thebillington** [comment]
Hi Walter,

Could you explain the steps you used to try run the code and let me know which version of Python you are using and what OS?

Also for reference there is a Youtube video explaining all of the steps needed to get the server running: https://www.youtube.com/watch?v=EYn2uTJkUSE&t=114s

**Comment by walterwang** [comment]
Installed the python3 branch of podsixnet, their examples worked for me. 
Then, I cloned this repository, and used python3 server.py and python3 game.py, that's when I get a connection refused error.

My os, is ubuntu 16.04  and python 3.5

**Comment by thebillington** [comment]
Hi Walter,

I built this using Python 2.7 and it's untested for Python 2.7. I know it's not much help but any chance you've got a Python 2 version you could use to test this?

Unfortunately I haven't had chance to play with PodSixNet on Python 3 yet and am unsure of any differences in the way connections are handled.

**Comment by walterwang** [comment]
Ok tested again in python2.7, everything works.
